name: Deploy to DEV S3
on:
  push:
    branches:
      - release-1.5.0

defaults:
  run:
    working-directory: .
    
jobs:
  build:
    name: Build Deploy To DEV S3
    environment: DEV
    runs-on: ubuntu-latest
    steps:
      - name: List contents
        run: |
          ls -lha
          
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.0.0
          
      - name: Install deps, and build
        run: |
          yarn install
          yarn workspace @shiksha/common-lib build
          yarn install
          yarn build
        env:          
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL_2 }}
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          REACT_APP_SENTRY_DSN_URL: ${{ secrets.REACT_APP_SENTRY_DSN_URL }}
          REACT_APP_SENTRY_ENV: ${{ secrets.REACT_APP_SENTRY_ENV }}
     
      - name: List contents
        run: |
          ls -lha
               
      - name: Create Lerna Bundles
        run: |
          sh ./scripts/pack-prod-build.sh

      - name: List contents
        run: |
          ls -lha
          
      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_S3_BUCKET_REGION }}
          SOURCE_DIR: prod-build


      # - name: Deploy to S3
      #   run: |
      #    aws s3 sync ./prod-build s3://eg-s3-bucket/ --delete --acl public-read
